ShopTarge24/Models/OpenWeather/OpenWeatherSearchViewModel.cs
namespace ShopTarge24.Models.OpenWeather
{
    public class OpenWeatherSearchViewModel
    {
        public string? CityName { get; set; }
    }
}

ShopTarge24/Models/OpenWeather/OpenWeatherViewModel.cs
namespace ShopTarge24.Models.OpenWeather
{
    public class OpenWeatherViewModel
    {
        public string CityName { get; set; } = string.Empty;
        public double? TempValue { get; set; }
        public double? TempFeelsLike { get; set; }
        public int Humidity { get; set; }
        public int Pressure { get; set; }
        public double WindSpeed { get; set; }
        public string? WeatherCondition { get; set; }

    }
}

ShopTarge24/Controllers/OpenWeatherController.cs
using Microsoft.AspNetCore.Mvc;
using ShopTarge24.ApplicationServices.Services;
using ShopTarge24.Models.OpenWeather;

namespace ShopTarge24.Controllers
{
    public class OpenWeatherController : Controller
    {
        private readonly OpenWeatherServices _openWeatherServices;

        public OpenWeatherController(OpenWeatherServices openWeatherServices)
        {
            _openWeatherServices = openWeatherServices;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchCity(OpenWeatherSearchViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }

            var weatherData = await _openWeatherServices.GetCityWeather(model.CityName);

            if (weatherData == null)
            {
                ViewBag.ErrorMessage = "City not found or API error";
                return View("Index", model);
            }

            return View("City", weatherData);
        }
    }
}

ShopTarge24/Views/OpenWeather/City.cshtml
@model ShopTarge24.Core.Dto.OpenWeatherRootDto

<div class="container">
    <h2>Forecast for the selected city</h2>
    <h2>@Html.DisplayFor(model => model.CityName)</h2>
    <hr />
    <dl class="row text-dark">
        <div>
            <dt class="col-sm-2">
                Temperature:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TempValue) °C
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Temp Feels like:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TempFeelsLike) °C
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Humidity:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Humidity) %
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Pressure:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Pressure) Hpa
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Wind Speed:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WindSpeed) Km/h
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Weather Condition:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WeatherCondition)
            </dd>
        </div>
    </dl>
</div>

ShopTarge24/Views/OpenWeather/Index.cshtml
@model ShopTarge24.Models.OpenWeather.OpenWeatherSearchViewModel

<h1>Search City</h1>

<div class="container">
    <form method="post">
        <div class="container">
            <div class="form-group col-md-offset-3 col-md-5">
                <h2>Search the forecast in a city</h2>
                <label asp-for="CityName"></label>
                <br />
                <input asp-for="CityName" class="form-control" />
                <span asp-validation-for="CityName" class="text-danger"></span>
            </div>
        </div>

        <hr />
        <div class="container">
            <div class="form-group col-md-offset-3 col-md-5">
                <button asp-controller="OpenWeather" asp-action="SearchCity" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>

    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger mt-3">
            @ViewBag.ErrorMessage
        </div>
    }
</div>