ShopTarge24/Models/Kindergarten/ImageViewModel.cs
namespace ShopTarge24.Models.Kindergarten
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? ImageTitle { get; set; }
        public string? Filepath { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }

        public Guid? KindergartenId { get; set; }
    }
}

ShopTarge24/Models/Kindergarten/KindergartenCreateUpdateViewModel.cs
using ShopTarge24.Models.Spaceships;

namespace ShopTarge24.Models.Kindergarten
{
    public class KindergartenCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? TeacherName { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<ImageViewModel> Image { get; set; }
            = new List<ImageViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}

ShopTarge24/Models/Kindergarten/KindergartenDeleteViewModel.cs
using ShopTarge24.Models.Spaceships;

namespace ShopTarge24.Models.Kindergarten
{
    public class KindergartenDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? KindergartenName { get; set; }
        public string? GroupName { get; set; }
        public string? TeacherName { get; set; }
        public int? ChildrenCount { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        // Lisame listi failide jaoks
        public List<ImageViewModel> Images { get; set; } = new List<ImageViewModel>();
    }
}

ShopTarge24/Models/Kindergarten/KindergartenDetailsViewModel.cs
using ShopTarge24.Models.Spaceships;

namespace ShopTarge24.Models.Kindergarten
{
    public class KindergartenDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? TeacherName { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public List<ImageViewModel> Images { get; set; }
            = new List<ImageViewModel>();

    }
}

ShopTarge24/Models/Kindergarten/KindergartenIndexViewModel.cs
namespace ShopTarge24.Models.Kindergarten
{ 
    public class KindergartenIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? TeacherName {  get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

    }
}

ShopTarge24/Models/Spaceships/ImageViewModel.cs
namespace ShopTarge24.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? Filepath { get; set; }
        public Guid? SpaceshipId { get; set; }
    }
}

ShopTarge24/Controllers/KindergartenController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTarge24.Core.Domain;
using ShopTarge24.Core.Dto;
using ShopTarge24.Core.ServiceInterface;
using ShopTarge24.Data;
using ShopTarge24.Models.Kindergarten;

namespace ShopTarge24.Controllers
{
    public class KindergartenController : Controller
    {
        private readonly ShopTarge24Context _context;
        private readonly IKindergartenServices _kindergartenServices;
        private readonly IFileServices _fileServices;

        public KindergartenController(
            ShopTarge24Context context,
            IKindergartenServices kindergartenServices,
            IFileServices fileServices)
        {
            _context = context;
            _kindergartenServices = kindergartenServices;
            _fileServices = fileServices;
        }

        public IActionResult Index()
        {
            var result = _context.Kindergartens
                .Select(x => new KindergartenIndexViewModel
                {
                    Id = x.Id,
                    GroupName = x.GroupName,
                    ChildrenCount = x.ChildrenCount,
                    KindergartenName = x.KindergartenName,
                    TeacherName = x.TeacherName
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("CreateUpdate", new KindergartenCreateUpdateViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id = Guid.NewGuid(),
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                TeacherName = vm.TeacherName,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files // Database failid
            };

            var result = await _kindergartenServices.Create(dto);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailAsync(id);
            if (kindergarten == null) return NotFound();

            var vm = new KindergartenCreateUpdateViewModel
            {
                Id = kindergarten.Id,
                GroupName = kindergarten.GroupName,
                ChildrenCount = kindergarten.ChildrenCount,
                KindergartenName = kindergarten.KindergartenName,
                TeacherName = kindergarten.TeacherName,
                CreatedAt = kindergarten.CreatedAt,
                UpdatedAt = kindergarten.UpdatedAt
            };

            vm.Image.AddRange(await GetFilesFromDatabase(id));

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                TeacherName = vm.TeacherName,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files
            };

            await _kindergartenServices.Update(dto);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailAsync(id);
            if (kindergarten == null) return NotFound();

            var vm = new KindergartenDeleteViewModel
            {
                Id = kindergarten.Id,
                GroupName = kindergarten.GroupName,
                ChildrenCount = kindergarten.ChildrenCount,
                KindergartenName = kindergarten.KindergartenName,
                TeacherName = kindergarten.TeacherName,
                CreatedAt = kindergarten.CreatedAt,
                UpdatedAt = kindergarten.UpdatedAt
            };

            vm.Images.AddRange(await GetFilesFromDatabase(id));
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            await _kindergartenServices.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailAsync(id);
            if (kindergarten == null) return NotFound();

            var vm = new KindergartenDetailsViewModel
            {
                Id = kindergarten.Id,
                GroupName = kindergarten.GroupName,
                ChildrenCount = kindergarten.ChildrenCount,
                KindergartenName = kindergarten.KindergartenName,
                TeacherName = kindergarten.TeacherName,
                CreatedAt = kindergarten.CreatedAt,
                UpdatedAt = kindergarten.UpdatedAt
            };

            vm.Images.AddRange(await GetFilesFromDatabase(id));
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveImage(Guid imageId, Guid kindergartenId)
        {
            // Kutsutakse service klassi meetod, mis kustutab FileToDatabase rea
            var success = await _kindergartenServices.RemoveImage(imageId);

            if (!success)
                return NotFound();

            // Pärast kustutamist jäädakse sama Kindergarten Details vaatesse
            return RedirectToAction("Details", new { id = kindergartenId });
        }

        private async Task<List<ImageViewModel>> GetFilesFromDatabase(Guid kindergartenId)
        {
            return await _context.FileToDatabases
                .Where(x => x.KindergartenId == kindergartenId)
                .Select(y => new ImageViewModel
                {
                    ImageId = y.Id,
                    KindergartenId = y.KindergartenId,
                    ImageTitle = y.ImageTitle,
                    ImageData = y.ImageData,
                    Image = $"data:image/gif;base64,{Convert.ToBase64String(y.ImageData)}"
                })
                .ToListAsync();
        }
    }
}

ShopTarge24/Views/Kindergarten/CreateUpdate.cshtml
@model ShopTarge24.Models.Kindergarten.KindergartenCreateUpdateViewModel

@if (Model.Id.HasValue)
{
	<h1>Update</h1>
}
else
{
	<h1>Create</h1>
}

<div>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="Id" type="hidden" />
		<input asp-for="CreatedAt" type="hidden" />
		<input asp-for="UpdatedAt" type="hidden" />

		<div class="form-group row">
			<label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="GroupName" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="ChildrenCount" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="KindergartenName" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="TeacherName" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="TeacherName" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="CreatedAt" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="Files" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-5">
				<div class="custom-file">
					<input class="form-control" asp-for="Files" multiple type="file" />
				</div>
			</div>
		</div>

		@foreach (var images in Model.Image)
		{
			<partial name="_Images" model="images" />
			<input asp-action="removeImage" asp-controller="kindergarten" asp-route-imageId="@images.ImageId" type="submit" class="btn btn-success" value="Remove Image" />
		}

		@if (Model.Id.HasValue)
		{
			<input asp-action="update" asp-controller="kindergarten" type="submit" class="btn btn-success" value="Update" />
		}
		else
		{
			<input asp-action="create" asp-controller="kindergarten" type="submit" class="btn btn-success" value="Create" />
		}

			<a asp-action="Index" asp-controller="kindergarten" class="btn btn-success">Back</a>
	</form>


</div>

ShopTarge24/Views/Kindergarten/Delete.cshtml
@model ShopTarge24.Models.Kindergarten.KindergartenDeleteViewModel

<h1>Delete</h1>

<div>
	<h4>Kindergarten</h4>
	<hr />
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Id"class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Id)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.GroupName)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.ChildrenCount)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.KindergartenName)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="TeacherName" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.TeacherName)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.CreatedAt)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.UpdatedAt)
		</div>
	</dl>

	<hr />
	<form asp-action="DeleteConfirmation">
		<input type="hidden" asp-for="Id"/>
		<input type="submit" value="Delete" class="btn btn-danger" />
		<a asp-action="Index" asp-controller="spaceships" class="btn btn-success">Back</a>
	</form>
</div>

ShopTarge24/Views/Kindergarten/Details.cshtml
@model ShopTarge24.Models.Kindergarten.KindergartenDetailsViewModel

<h1>Kindergarten Details</h1>

<div>
    <h4>Kindergarten Info</h4>
    <hr />

    <dl class="row">
        <dt class="col-sm-2">ID</dt>
        <dd class="col-sm-10">@Model.Id</dd>

        <dt class="col-sm-2">Group Name</dt>
        <dd class="col-sm-10">@Model.GroupName</dd>

        <dt class="col-sm-2">Children Count</dt>
        <dd class="col-sm-10">@Model.ChildrenCount</dd>

        <dt class="col-sm-2">Kindergarten Name</dt>
        <dd class="col-sm-10">@Model.KindergartenName</dd>

        <dt class="col-sm-2">Teacher Name</dt>
        <dd class="col-sm-10">@Model.TeacherName</dd>

        <dt class="col-sm-2">Created At</dt>
        <dd class="col-sm-10">@Model.CreatedAt</dd>

        <dt class="col-sm-2">Updated At</dt>
        <dd class="col-sm-10">@Model.UpdatedAt</dd>
    </dl>

    <h4>Images</h4>
    <div class="row">
        @foreach (var image in Model.Images)
        {
            <div class="col-md-3 text-center mb-3">
                <img src="@image.Image" class="img-thumbnail" alt="@image.ImageTitle" />

                <form asp-action="RemoveImage"
                      asp-controller="Kindergarten"
                      method="post"
                      class="mt-2">
                    @Html.AntiForgeryToken()
                    <input type="hidden" name="imageId" value="@image.ImageId" />
                    <input type="hidden" name="kindergartenId" value="@Model.Id" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Delete
                    </button>
                </form>
            </div>
        }
    </div>

    <hr />
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

ShopTarge24/Views/Kindergarten/Index.cshtml
@model IEnumerable<ShopTarge24.Models.Kindergarten.KindergartenIndexViewModel>


<div>
	<a asp-action="create" asp-controller="Kindergarten" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
	Kindergarten
</div>
<form method="post">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col">Nr</th>
				<th scope="col">Group Name</th>
				<th scope="col">Children</th>
				<th scope="col">Kindergarten name</th>
				<th scope="col">Teacher</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			@{
				int nr = 1;
			}
			@foreach (var kindergarten in Model)
			{
				<tr>
					<td>@nr</td>
					<td>@kindergarten.GroupName</td>
					<td>@kindergarten.ChildrenCount</td>
					<td>@kindergarten.KindergartenName</td>
					<td>@kindergarten.TeacherName</td>
					<td>
						<a asp-action="update" asp-controller="kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-primary">Update</a>
						<a asp-action="delete" asp-controller="kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-outline-danger">Delete</a>
						<a asp-action="details" asp-controller="kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-primary">Details</a>
					</td>
				</tr>
				nr++;
			}
		</tbody>
	</table>
</form>

ShopTarge24/Views/Kindergarten/_Images.cshtml
@model ShopTarge24.Models.Kindergarten.ImageViewModel

@{
    var photoPaths = "~/multipleFileUpload/" + (Model.Filepath ?? "noimage.jpg");
}

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.Filepath</div>
    <img class="card-image-top" src="@photoPaths" asp-append-version="true" />
</div>